development:
  adapter: postgresql
  encoding: unicode
  database: home_budget_development
  pool: 5
  username: davidortizfrau
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: home_budget_test
  pool: 5
  username: davidortizfrau
  password:

